# server 
server:
  port: 8888
  context: path=/
  
---

# profiles
spring:
  profiles:
    active: dev

---

# spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jpa?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
    username: root
    password: 123456
    
---

# jpa
spring:
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    
---

# reids
spring:
  redis:
    database: 7
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 1500
    
---
    
# session 分布式会话共享
spring:
  session:
    store-type: redis
    
---

# log
logging:
  file: logback-spring.xml
  
---

# springmvc
spring:
  view:
    prefix: /
    suffix: .jsp
